### ISSUE TITLE
Transform Bind account (EVM) widget to a popup

### ISSUE THREAD

**Issue by lukalocniskar** [reef-defi/reef-app#136]
Bind account should become a button in the header if accounts needs binding. Once pressed, user should be presented with a popup with current content "Register Ethereum VM Address"

On opening app with a wallet that needs binding, user should be promped with this same popup.

**Comment by samoslag** [comment]
Implemented.
Bind account link in navigation has been replaced with permanent notification, due to it being more noticable.
Bind component has also been restyled to match new design.

![Untitled-1](https://user-images.githubusercontent.com/59774151/186665211-d3b3c66f-5989-48f4-92ff-d623bf05f298.jpg)
![Untitled-2](https://user-images.githubusercontent.com/59774151/186665213-e070abeb-20d6-432e-b21e-241f9b4b2745.jpg)
